runtest: allow naming of output file

diff --git a/bin/runtest b/bin/runtest
--- a/bin/runtest
+++ b/bin/runtest
@@ -14,10 +14,13 @@ function show_help() {
   echo "  Build and run the tests"
   echo ""
   echo "Options:"
-  echo "  -j=N|--make-j=N       Build the tests in parallel"
-  echo "  --build-only          Only build the tests"
-  echo "  -v|--verbose          Tee STDOUT and STDERR to screen and files"
-  echo "  -h|--help             Show this message"
+  echo "  -j=N|--make-j=N        Build the tests in parallel"
+  echo "  -c|--clean             Clean build and regenerate make files"
+  echo "  --clean-on-pass        Clean build when runtest passes"
+  echo "  --output-prefix=<pre>  Prefix of log files  Default: runtest"
+  echo "  --build-only           Only build the tests"
+  echo "  -v|--verbose           Tee STDOUT and STDERR to screen and files"
+  echo "  -h|--help              Show this message"
   echo ""
   ${KOKKOS_PATH}/generate_makefile.bash --help
   return 0
@@ -27,7 +30,9 @@ function show_help() {
 declare -a GENERATE_ARGS=()
 declare -i VERBOSE=0
 declare -i CLEAN=0
+declare -i CLEAN_ON_PASS=0
 declare -i BUILD_ONLY=0
+OUTPUT="runtest"
 
 declare -i MAKE_J=${HPCBIND_NUM_PUS:-1}
 
@@ -37,16 +42,24 @@ for i in $@; do
       MAKE_J=${i#*=}
       shift
       ;;
+    -c|--clean)
+      CLEAN=1
+      shift
+      ;;
+    --clean-on-pass)
+      CLEAN_ON_PASS=1
+      shift
+      ;;
+    --output-prefix=*)
+      OUTPUT=${i#*=}
+      shift
+      ;;
     --build-only)
       BUILD_ONLY=1
       shift
       ;;
     -v|--verbose)
       VERBOSE=1
-      shift
-      ;;
-    -c|--clean)
-      CLEAN=1
       shift
       ;;
     -h|--help)
@@ -60,15 +73,33 @@ for i in $@; do
   esac
 done
 
+if [[ "$(pwd -P)" == ${KOKKOS_PATH} ]]; then
+  echo "Cannot call $0 from root repository path ${KOKKOS_PATH}"
+  exit 1
+fi
+
+# Some makefile dependencies are incorrect, so clean needs to force
+# a new call to generate_makefiles.bash
+if [[ ${CLEAN} -eq 1 ]]; then
+  START=${SECONDS}
+  echo "Cleaning"
+  /bin/rm -rf algorithms containers core example install Makefile >/dev/null 2>&1
+  END=${SECONDS}
+  echo "    $((END-START)) seconds"
+  if [[ ${VERBOSE} -eq 1 ]]; then
+    echo ""
+    echo ""
+  fi
+fi
 
 declare -i START=${SECONDS}
 echo "Generating Makefile"
 echo "    ${KOKKOS_PATH}/generate_makefile.bash --kokkos-path=${KOKKOS_PATH} ${GENERATE_ARGS[@]}"
 
 if [[ ${VERBOSE} -eq 0 ]]; then
-  "${KOKKOS_PATH}"/generate_makefile.bash --kokkos-path="${KOKKOS_PATH}" "${GENERATE_ARGS[@]}" > runtest_generate.log 2> >(tee -a runtest_generate.err >&2)
+  "${KOKKOS_PATH}"/generate_makefile.bash --kokkos-path="${KOKKOS_PATH}" "${GENERATE_ARGS[@]}" > ${OUTPUT}.out 2> >(tee ${OUTPUT}.err >&2)
 else
-  "${KOKKOS_PATH}"/generate_makefile.bash --kokkos-path="${KOKKOS_PATH}" "${GENERATE_ARGS[@]}" > >(tee -a runtest_generate.log) 2> >(tee -a runtest_generate.err >&2)
+  "${KOKKOS_PATH}"/generate_makefile.bash --kokkos-path="${KOKKOS_PATH}" "${GENERATE_ARGS[@]}" > >(tee ${OUTPUT}.out) 2> >(tee ${OUTPUT}.err >&2)
 fi
 declare -i RESULT=$?
 declare -i END=${SECONDS}
@@ -79,34 +110,18 @@ if [[ ${RESULT} -eq 0 ]]; then
     echo ""
   fi
 else
-  cat runtest_generate.log | grep "FAIL"
-  cat runtest_generate.err | grep "FAIL"
+  cat ${OUTPUT}.out | grep "FAIL"
+  cat ${OUTPUT}.err | grep "FAIL"
   echo "    FAIL:  $((END-START)) seconds"
   exit 1
-fi
-
-if [[ ${CLEAN} -eq 1 ]]; then
-  START=${SECONDS}
-  echo "Cleaning"
-  if [[ ${VERBOSE} -eq 0 ]]; then
-    make --keep-going -j ${MAKE_J} clean > runtest_clean.log 2> >(tee -a runtest_clean.err >&2)
-  else
-    make --keep-going -j ${MAKE_J} clean > >(tee -a runtest_clean.log) 2> >(tee -a runtest_clean.err >&2)
-  fi
-  END=${SECONDS}
-  echo "    $((END-START)) seconds"
-  if [[ ${VERBOSE} -eq 1 ]]; then
-    echo ""
-    echo ""
-  fi
 fi
 
 START=${SECONDS}
 echo "Building"
 if [[ ${VERBOSE} -eq 0 ]]; then
-  make --keep-going -j ${MAKE_J} build-test > runtest_build.log 2> >(tee -a runtest_build.err >&2)
+  make --keep-going -j ${MAKE_J} build-test >> ${OUTPUT}.out 2> >(tee -a ${OUTPUT}.err >&2)
 else
-  make --keep-going -j ${MAKE_J} build-test > >(tee -a runtest_build.log) 2> >(tee -a runtest_build.err >&2)
+  make --keep-going -j ${MAKE_J} build-test > >(tee -a ${OUTPUT}.out) 2> >(tee -a ${OUTPUT}.err >&2)
 fi
 RESULT=$?
 END=${SECONDS}
@@ -117,8 +132,8 @@ if [[ ${RESULT} -eq 0 ]]; then
     echo ""
   fi
 else
-  cat runtest_build.log | grep -E "[[:space:]]error:[[:space:]]"
-  cat runtest_build.err | grep -E "[[:space:]]error:[[:space:]]"
+  cat ${OUTPUT}.out | grep -E "[[:space:]]error:[[:space:]]"
+  cat ${OUTPUT}.err | grep -E "[[:space:]]error:[[:space:]]"
   echo "    FAIL:  $((END-START)) seconds"
   exit 1
 fi
@@ -127,18 +142,23 @@ if [[ ${BUILD_ONLY} -eq 0 ]]; then
   START=${SECONDS}
   echo "Testing"
   if [[ ${VERBOSE} -eq 0 ]]; then
-    make --keep-going test > runtest_test.log 2> >(tee -a runtest_test.err >&2)
+    make --keep-going test >> ${OUTPUT}.out 2> >(tee -a ${OUTPUT}.err >&2)
   else
-    make --keep-going test > >(tee -a runtest_test.log) 2> >(tee -a runtest_test.err >&2)
+    make --keep-going test > >(tee -a ${OUTPUT}.out) 2> >(tee -a ${OUTPUT}.err >&2)
   fi
   RESULT=$?
   END=${SECONDS}
   if [[ ${RESULT} -eq 0 ]]; then
     echo "    PASS:  $((END-START)) seconds"
+    if [[ ${CLEAN_ON_PASS} -eq 1 ]]; then
+      make clean
+    fi
   else
-    cat runtest_test.log | grep "FAIL"
-    cat runtest_test.err | grep "FAIL"
+    cat ${OUTPUT}.out | grep "FAIL"
+    cat ${OUTPUT}.err | grep "FAIL"
     echo "    FAIL:  $((END-START)) seconds"
     exit 1
   fi
 fi
+
+return ${RESULT}
