Allow CEA nightly build to fail (#7792)
* Allow CEA nightly build to fail if one step with continue-on-error failed

* [skip appveyor] Allow to run on pull request

* [ci skip] Revert "[skip appveyor] Allow to run on pull request"

This reverts commit e8d759523bc1e569fd21efa448756c2db4b0ad71.

diff --git a/.github/workflows/nightly-cea.yml b/.github/workflows/nightly-cea.yml
--- a/.github/workflows/nightly-cea.yml
+++ b/.github/workflows/nightly-cea.yml
@@ -69,6 +69,7 @@ jobs:
               ${{ matrix.backend.configure }}
 
       - name: Start, update and configure
+        id: start_update_configure
         continue-on-error: true
         run: |
           run \
@@ -82,6 +83,7 @@ jobs:
               -D NightlyConfigure
 
       - name: Build
+        id: build
         continue-on-error: true
         run: |
           run \
@@ -94,6 +96,7 @@ jobs:
               -D NightlyBuild
 
       - name: Test
+        id: test
         continue-on-error: true
         run: |
           run \
@@ -112,3 +115,14 @@ jobs:
             ctest \
               --test-dir build \
               -D NightlySubmit
+
+      # note: this marks the job as failed if any of the mentionned steps (that
+      # have `continue-on-error`) has failed
+      - name: Failure outcome
+        if: |-
+          ${{
+            steps.start_update_configure.outcome == 'failure' ||
+            steps.build.outcome == 'failure' ||
+            steps.test.outcome == 'failure'
+          }}
+        run: exit 1
