Fix the skip logic for md files
Required Jobs would show as not passed even if they
don't run because they are filtered out.
So we need to make the Required Aggregate job run always,
but skip the individual jobs, and adjust the pass logic of the
required job.

Signed-off-by: Christian Trott <crtrott@sandia.gov>

diff --git a/.github/workflows/snl-ci.yml b/.github/workflows/snl-ci.yml
--- a/.github/workflows/snl-ci.yml
+++ b/.github/workflows/snl-ci.yml
@@ -2,8 +2,6 @@ name: SNL-CI
 
 on:
   pull_request:
-    paths-ignore:
-    - '**/*.md'
     types: [ opened, reopened, synchronize ]
 
 permissions:
@@ -15,8 +13,23 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  SNL_NeedChecks:
+    name: SNL_NeedChecks
+    runs-on: ubuntu-latest
+    outputs:
+      code: ${{ steps.filter.outputs.code }}
+    steps:
+      - uses: dorny/paths-filter@v3
+        id: filter
+        with:
+          filters: |
+            code:
+              - '!**/*.md'
+
   SNL_CUDA_NVCC_12_2_CPP20:
     name: SNL_CUDA_NVCC_12_2_CPP20
+    needs: SNL_NeedChecks
+    if: needs.SNL_NeedChecks.outputs.code == 'true'
     runs-on: [snl-kk-env-cuda-12.2.0-gcc-11.3.0-latest]
 
     strategy:
@@ -77,6 +90,8 @@ jobs:
 
   SNL_HIP_ROCM_6_2_1_CPP23:
     name: SNL_HIP_ROCM_6_2_1_CPP23
+    needs: SNL_NeedChecks
+    if: needs.SNL_NeedChecks.outputs.code == 'true'
     runs-on: [rocm-6.2.1_openblas-0.3.28_zen3_gfx90a-latest-latest]
 
     steps:
@@ -131,6 +146,8 @@ jobs:
 
   SNL_HIP_ROCM_6_2_1:
     name: SNL_HIP_ROCM_6_2_1
+    needs: SNL_NeedChecks
+    if: needs.SNL_NeedChecks.outputs.code == 'true'
     runs-on: [rocm-6.2.1_openblas-0.3.28_zen3_gfx90a-latest-latest]
 
     steps:
@@ -186,6 +203,8 @@ jobs:
 
   SNL_OPENMP_SERIAL_INTEL_2024_2_1:
     name: SNL_OPENMP_SERIAL_INTEL_2024_2_1
+    needs: SNL_NeedChecks
+    if: needs.SNL_NeedChecks.outputs.code == 'true'
     runs-on: [inteloneapi-basekit-2024.2.1-0-devel-ubuntu22.04-latest-spr]
 
     strategy:
@@ -244,6 +263,8 @@ jobs:
 
   SNL_SYCL_INTEL_2024_2_1:
     name: SNL_SYCL_INTEL_2024_2_1
+    needs: SNL_NeedChecks
+    if: needs.SNL_NeedChecks.outputs.code == 'true'
     runs-on: [inteloneapi-basekit-2024.2.1-0-devel-ubuntu22.04-latest-pv]
 
     steps:
@@ -296,6 +317,8 @@ jobs:
 
   SNL_SERIAL_LLVM_14_0_6:
     name: SNL_SERIAL_LLVM_14_0_6
+    needs: SNL_NeedChecks
+    if: needs.SNL_NeedChecks.outputs.code == 'true'
     runs-on: [llvm-14.0.6_x86-64-latest-latest]
 
     steps:
@@ -330,6 +353,8 @@ jobs:
 
   SNL_SERIAL_CLANG_19_MODULES:
     name: SNL_SERIAL_CLANG_19_MODULES
+    needs: SNL_NeedChecks
+    if: needs.SNL_NeedChecks.outputs.code == 'true'
     runs-on: [clang-19_gcc-15.1_x86-64-latest]
 
     steps:
@@ -368,6 +393,8 @@ jobs:
 # FIXME_HPX: workaround for standard library calling OOM handler for failing nothrow new, remove once fixed
   SNL_HPX_GCC_15_1_1:
     name: SNL_HPX_GCC_15_1_1
+    needs: SNL_NeedChecks
+    if: needs.SNL_NeedChecks.outputs.code == 'true'
     runs-on: [ci-containersfedora-latest-latest]
 
     steps:
@@ -414,6 +441,8 @@ jobs:
 
   SNL_OPENACC_CUDA_12_2_NVHPC_23_7_CPP20:
     name: SNL_OPENACC_CUDA_12_2_NVHPC_23_7_CPP20
+    needs: SNL_NeedChecks
+    if: needs.SNL_NeedChecks.outputs.code == 'true'
     runs-on: [cuda-12.2_nvhpc-23.7_x86-64-latest]
 
     steps:
@@ -453,6 +482,8 @@ jobs:
 
   SNL_NextSilicon_Latest:
     name: SNL_NextSilicon_Latest
+    needs: SNL_NeedChecks
+    if: needs.SNL_NeedChecks.outputs.code == 'true'
     runs-on: [next-latest]
 
     steps:
@@ -527,11 +558,13 @@ jobs:
         run: |
           ulimit -c 0
           ctest -V --timeout 1800
+
   SNL_Required_Checks:
     if: always()
     name: SNL_Required_Checks
     # bash command to collect this: [grep "name: SNL_" snl-ci.yml | awk '{print "      - "$3}']
     needs:
+      - SNL_NeedChecks
       - SNL_CUDA_NVCC_12_2_CPP20
       - SNL_HIP_ROCM_6_2_1_CPP23
       - SNL_HIP_ROCM_6_2_1
@@ -546,13 +579,16 @@ jobs:
     steps:
       - name: Require all checks to pass
         run: |
-          if [[ \
-            "${{ contains(needs.*.result, 'failure') }}" == "true" || \
-            "${{ contains(needs.*.result, 'cancelled') }}" == "true" || \
-            "${{ contains(needs.*.result, 'skipped') }}" == "true" \
-          ]]; then
-            echo "At least one required SNL job did not succeed."
-            exit 1
+          if [[ "${{ needs.SNL_NeedChecks.outputs.code }}" == "true" ]]; then
+            # code changed: no job should be skipped/failed/cancelled
+            if [[ \
+              "${{ contains(needs.*.result, 'failure') }}" == "true" || \
+              "${{ contains(needs.*.result, 'cancelled') }}" == "true" || \
+              "${{ contains(needs.*.result, 'skipped') }}" == "true" \
+            ]]; then
+              echo "At least one required SNL job did not succeed."
+              exit 1
+            fi
           fi
 
           echo "All required SNL jobs succeeded."
